### ISSUE TITLE
Implement drawer menu

### ISSUE THREAD

**Issue by kuzn-ilya** [kuzn-ilya/ryazan#16]
![Untitled-1](https://user-images.githubusercontent.com/7905573/59904819-2eabaf80-940d-11e9-8ff5-5701ca564bbd.png)

**Comment by lxndr** [comment]
It's best to replace `react-navigation-drawer` with `react-native-gesture-handler/DrawerLayout` and move drawer screens into the stack navigator. I checked and it works a lot faster but still has the issue with the map.

[This](https://kmagiera.github.io/react-native-gesture-handler/docs/interactions.html) is probably how to make map and drawer work together. And [A bunch of examples](https://github.com/kmagiera/react-native-gesture-handler/tree/master/Example).

**Comment by eugrdn** [comment]
Do you mean by `react-navigation-drawer` a drawer from `react-navigation`, don't you?

**Comment by lxndr** [comment]
Yes. Not so long ago they started to split `react-navigation`.
