### ISSUE TITLE
"Share" button does something strange

### ISSUE THREAD

**Issue by kuzn-ilya** [kuzn-ilya/ryazan#65]
Share button sends mesasage like "Check out Консисторский корпус at улица Кремль, 11". We need to come up with an idea how to make it more useful

**Comment by eugrdn** [comment]
you might need to use deep-linking here, e.g https://branch.io/what-is-deep-linking/

**Comment by lxndr** [comment]
I guess RN sharing feature uses deep liking under the hood. I don't see any reason to use it directly, not until we decide what this button has to do.

**Comment by lxndr** [comment]
the plan is:

- the user presses "share" button and that sends a special link.
- pressing the link opens our app and navigates to specific screen, if the app wasn't installed, it opens our store page.

https://branch.io/
https://docs.expo.io/versions/latest/workflow/linking/
https://reactnavigation.org/docs/en/deep-linking.html

**Comment by lxndr** [comment]
In case we use branch.io, links like "*.app.link" are banned by epam network. Also, we need store ids for both ios and android.
