### ISSUE TITLE
No ability to display more than 1 photo for POI in details

### ISSUE THREAD

**Issue by Multitester** [kuzn-ilya/ryazan#75]
You can check it on Памятник Евпатию Коловрату POI

**Comment by lxndr** [comment]
It will be implemented after redesign.

**Comment by Multitester** [comment]
OK. So promptly

**Comment by lxndr** [comment]
look promising: https://github.com/leecade/react-native-swiper
on second thought - it can be added right now

**Comment by Multitester** [comment]
ok. looks good
